### ISSUE TITLE
Compiling Error during cosmos compile

### ISSUE THREAD

**Issue by mitchellurgero** [aura-systems/Aura-Operating-System#103]
I am not able to compile correctly on the latest version of Windows 10. It begins the build process but fails stating something about a process terminating?

I have followed the instructions on the website and the result is the same for me

Log attached.
[error_log.txt](https://github.com/aura-systems/Aura-Operating-System/files/2462639/error_log.txt)

**Comment by Project-Magenta** [comment]
You need to install .NET Framework 4.7.1

**Comment by Project-Magenta** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=56119

**Comment by mitchellurgero** [comment]
I have 4.7.1 installed however. I am not in front of my computer to confirm it at the moment, but I suppose it's worth a look. I'll be back on when I can to confirm or not.

**Comment by geomtech** [comment]
Hello,
You have the error during the installation of cosmos ?
Can you verify if you have the good version of .net framework but also .net framework developer pack 😅
Also, the cosmos directory have to be in the same directory where there are IL2CPU and Xsharp.
Please use only our versions of those, located in aura-systems/ on GitHub 😁 (we did some modifications)

**Comment by valentinbreiz** [comment]
Hello @mitchellurgero. I made a small tutorial on our website. If you want to make sure you did it like you should: http://aura-team.com/compileaura.html

**Comment by mitchellurgero** [comment]
@valentinbreiz if you are talking about "http://aura-team.com/compileaura.html" I followed that to the letter.

**Comment by valentinbreiz** [comment]
Ah ah ok x)
So it's weird.. It's seems to be a SDK problem.. Are you sure you have installed the Developer Pack ?

**Comment by mitchellurgero** [comment]
@valentinbreiz I'll be able to check when I am off work tonight. :)

**Comment by mitchellurgero** [comment]
@all - I managed to get it working. Apparently I missed a step because rebuilding my dev machine and following the steps again worked.

**Comment by valentinbreiz** [comment]
Cool!
