### ISSUE TITLE
Aura's Cosmos modified kernel won't install.

### ISSUE THREAD

**Issue by danbulant** [aura-systems/Aura-Operating-System#110]
Hello. When I start vs2017.bat it after some time show this error:
========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process)
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by geomtech** [comment]
Hello !

Thanks for trying to work on Aura.
To be able to help you, I need to have some informations...
Did you download all the repositories that are required for Aura ?
- Aura OS
- Common
- Cosmos
- IL2CPU
- XSharp
After that, you will have to make a directory and put them all in the same :)
![image](https://user-images.githubusercontent.com/5628290/50374613-0aebe600-05f1-11e9-823b-778b4e23bd33.png)
Like that ^^
Tip : You can make a fork of all the repositories and clone them in local into the same directory.

If you did it and it's not working, did you install all the prerequisites ?
- Latest version of VS 2017
- .NET Core SDK 2.1
- Inno Quick Start Pack (Free) – Install with defaults, keep Preprocessor option checked
- Visual Studio 2017 Workload: Visual Studio Extension Development
- .NET Framework 4.7.1 Developer Pack

I hope that will help you :-)
If it's not working after that, you can tell me here or on our Discord ;)

Best regards,
Alexy DA CRUZ.

**Comment by danbulant** [comment]
Hello.
I checked everything you said, and only problem I had was naming (-master) and the folders (cosmos inside  aura os), but it fails with same error.
Full cosmos console (Got that by clicking on that "copy" button) can be found here:
[Cosmos error log at my website](http://danbulant.eu/cosmos-error-log.txt)

**Comment by geomtech** [comment]
Hi Daniel,

Thanks for the logs! 👍 

``
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\Dan\Downloads\Aura-Operating-System-master\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows_4tqb1ffb_wpftmp.csproj]
  Cosmos.System2_Plugs -> C:\Users\Dan\Downloads\Aura-Operating-System-master\Cosmos\Build\VSIP\Cosmos.System2_Plugs.dll
``

We can see that you don't have .NET Framework 4.7.1 SDK installed.
Here the link to download it : https://www.microsoft.com/en-us/download/details.aspx?id=56119

Best regards,
Alexy DA CRUZ.

**Comment by danbulant** [comment]
Thanks.. I though I have it, but found that I have NDP472...

**Comment by geomtech** [comment]
No problem! ;-)
Tell me if it's working :p

**Comment by danbulant** [comment]
Also, because the dev kit didn't build, why the user kit worked?

**Comment by danbulant** [comment]
Didn't work, look like the same error (updated the log file)...

**Comment by geomtech** [comment]
Devkit = master of Cosmos, so when they're making some modifications, it's possible that you're not able to build Cosmos.... :/
But we're not doing the same, and normally it works... I installed our cosmos on a computer from school lol x: recently...
I don't think it's because of your computer, I already ran our Cosmos modified version and Aura on a older computer...

Can you try to install .NET Core SDK 2.2 ?

**Comment by danbulant** [comment]
Already did, but will try again

**Comment by geomtech** [comment]
2.2 ? and do you have the 2.1 version installed ?

**Comment by danbulant** [comment]
yeah, I have both, but it looks there is new version of 2.2. Will try again and report if it worked

**Comment by danbulant** [comment]
Still the same error happened. I used diffchecker and it looks barely the same except some parts were in different position (some restores have swapped), but it's probably normal... This same error happens when I try to build normal cosmos dev kit... I realy don't know  why

**Comment by geomtech** [comment]
I'm at work so I'm not able to see which versions I have on my computer but when I will be at home, I send a screen with all the versions that are installed on my computer.

**Comment by geomtech** [comment]
Hey,
So, this is all the version that are installed on my computer : 
![image](https://user-images.githubusercontent.com/5628290/50457722-255df080-095e-11e9-9e5a-2f644e8e8186.png)
(from the settings page on windows 10)

Could you try to install .NET Core 2.0 ?

Regards,
Alexy DA CRUZ
