### ISSUE TITLE
VS 2019 Build error

### ISSUE THREAD

**Issue by kissggj123** [aura-systems/Aura-Operating-System#114]
Exception: System.Exception: Error compiling method 'SystemVoidAura_OSKernelBeforeRun': System.Exception: OpCode IL_007D: Ldflda tries to pop item at stack position 0 with type Aura_OS.Core.VBE+ModeInfo&, but actual type is System.IntPtr
![image](https://user-images.githubusercontent.com/8959123/72206879-df72bc80-34cd-11ea-8b1c-0552bce06ad7.png)

**Comment by valentinbreiz** [comment]
I have the same problem, trying to fix it

**Comment by jas777** [comment]
I have the same problem

**Comment by valentinbreiz** [comment]
The issue has been located we're working on a fix

**Comment by valentinbreiz** [comment]
https://github.com/aura-systems/Aura-Operating-System/issues/119

**Comment by valentinbreiz** [comment]
@jas777 @kissggj123 it can compiles now but the issue isn't fixed
