### ISSUE TITLE
Filesystem

### ISSUE THREAD

**Issue by zaiinn-x** [aura-systems/Aura-Operating-System#115]
When I boot AuraOS, I get this `No volumes are detected, filesystem is disabled!`

I downloaded the iso image

**Comment by valentinbreiz** [comment]
On what are you booting the ISO? VMWare? Real Hardware?

**Comment by zaiinn-x** [comment]
VMWare

**Comment by TFTWPhoenix** [comment]
Try using the attached VMDK. Cosmos (the os this is based on) needs this for vmware. Here is the wiki page: https://github.com/CosmosOS/Cosmos/wiki/FAT-FileSystem

VMDK:

[filesystemvmdk.zip](https://github.com/aura-systems/Aura-Operating-System/files/4790099/filesystemvmdk.zip)

**Comment by geomtech** [comment]
Solved.
