### ISSUE TITLE
Implement a good text editor

### ISSUE THREAD

**Issue by valentinbreiz** [aura-systems/Aura-Operating-System#151]
~~Something like https://github.com/WilliamRagstad/ConsoleCodeEditor~~

Or https://github.com/Haydend/TEXT

**Comment by AnErrupTion** [comment]
For something more simplistic, maybe https://github.com/bartashevich/MIV?

**Comment by valentinbreiz** [comment]
@AnErrupTion, MIV is now implemented thanks for sharing
