### ISSUE TITLE
Compile Error at project

### ISSUE THREAD

**Issue by MasterYuan418** [aura-systems/Aura-Operating-System#194]
I encountered an error during the compilation process. Visual Studio reported CS0234 and could not find packages such as Cosmos.System.Network.Config.

**Comment by MasterYuan418** [comment]
![Image](https://user-images.githubusercontent.com/58651976/107023963-54ecb180-67e2-11eb-9d94-7df9919aa9d9.png)

**Comment by valentinbreiz** [comment]
Hello @MasterYuan418, did you build our version of the Cosmos devkit before trying to build AuraOS ?

**Comment by MasterYuan418** [comment]
thanks so much!Now I build aura os successfully!
