### ISSUE TITLE
How i set internet to work?

### ISSUE THREAD

**Issue by aleOS2** [aura-systems/Aura-Operating-System#198]
What is it the {Device} {IPV4} {GATEWAY} 
Is the Vmware on my ipconfig on Windows cmd? You can help me? Tranks!

**Comment by valentinbreiz** [comment]
Hello! To manually set an IP thought the ipconfig command you have to type something like that:
ipconfig /set eth0 192.168.1.12/24 192.168.1.1
If you don't know what addresses to put you can type ipconfig in your Windows terminal to get your local IP, mask and gateway. Of course don't use the IP of your computer, use a new and unused IP,

**Comment by alessiobb1** [comment]
Hi... But what device i can put, if i put eth0 i have an error of not found eth0... in my ipconfig on Windows cmd i have some devices, Ethernet Wifi Vmware and Bluethoot

Sorry if my english is not perfect but i'm italian.

**Comment by MasterYuan418** [comment]
Maybe you should re-install VMware...In my VMware,the `ipconfig /set eth0 192.168.1.12/24 192.168.1.1` can successful run.

**Comment by Kiirx** [comment]
Hi @aleOS2, is this problem still occuring with the last commit? if it doesnt, please close the issue.

**Comment by valentinbreiz** [comment]
Hello @aleOS2, since DHCP is now implemented you can just type ipconfig /ask
