### ISSUE TITLE
GNOME Boxes (QEMU) Display Blank

### ISSUE THREAD

**Issue by MadelynWith5Ns** [aura-systems/Aura-Operating-System#200]
![Screenshot from 2021-04-15 22-51-40](https://user-images.githubusercontent.com/61560519/114969079-4273a180-9e3d-11eb-91ef-0c31f44cf8bc.png)

As shown in the above screenshot when booting in GNOME Boxes (QEMU/KVM) on Arch Linux the screen is blank except for a line at the bottom of the screen. Is this still a Cosmos thing or a known bug?

**Comment by TFTWPhoenix** [comment]
UPDATE: I'm fairly positive this is a Cosmo thing given that Cosmos only supports VMWare and HyperV

**Comment by valentinbreiz** [comment]
I don't think it's a Cosmos issue, we already had Qemu working in textmode

**Comment by valentinbreiz** [comment]
Okay so it's an issue with VBE using qemu
Since you now can choose textmode at boot time you can only use textmode with qemu
