### ISSUE TITLE
os wont even load in VS2019

### ISSUE THREAD

**Issue by awipslinuxuser** [aura-systems/Aura-Operating-System#209]

**Comment by awipslinuxuser** [comment]
the os wont even load

**Comment by awipslinuxuser** [comment]
yes i installed every recommended app on the list

**Comment by valentinbreiz** [comment]
Can you please send me a screenshot or logs describing your issue?

**Comment by awipslinuxuser** [comment]
ok hold on

**Comment by awipslinuxuser** [comment]
![first issue](https://user-images.githubusercontent.com/67390756/122581048-43cb7100-d01c-11eb-8744-445a94e3d5c0.png)
![hello files](https://user-images.githubusercontent.com/67390756/122581049-44640780-d01c-11eb-8af0-9f7cf98f58ea.png)
![NO FILES ](https://user-images.githubusercontent.com/67390756/122581050-44640780-d01c-11eb-9433-5300749a1d35.png)

**Comment by valentinbreiz** [comment]
First of all you should never open a VS project without unzipping it

**Comment by MasterYuan418** [comment]
Emmmm.... You should unzip this file, then open the .sln file. :(

**Comment by Kiirx** [comment]
I think this issue can be closed
