### ISSUE TITLE
Aura_OSBoot

### ISSUE THREAD

**Issue by hellisabove** [aura-systems/Aura-Operating-System#210]
When I try to compile Aura_Plugs i get the error that is found in the wiki when compilling. The wiki says to put 'Aura_OSBoot' as a startup project but I can't find it. Where is it?

**Comment by MasterYuan418** [comment]
Emmm.... I guess you should open your Visual Studio's Solution Explorer and right click project 'Aura_OS', then set as startup project.
Like that:
![屏幕截图 2021-08-19 091851.png](https://i.loli.net/2021/08/19/AJM3i6WSaZxtBdE.png)
Aura_OS will be bold and highlight.
