### ISSUE TITLE
How can I convert a TTF or OTF file to PSF?

### ISSUE THREAD

**Issue by MasterYuan418** [aura-systems/Aura-Operating-System#212]
I search at the Internet for how to convert TTF or OTF font file to PSF file.But I just found the OSDev Wiki and Unifoundry.How can I convert a TTF or OTF file to PSF?
 I found a font from http://unifoundry.com/unifont/index.html called 'Unifont'. But It's dosen't work at sources code.I just convert this PSF file to base64.Should I do more steps?Or May I do some wrong?
 Thanks a lot.

**Comment by valentinbreiz** [comment]
TTF or OTF are vectorial fonts and PSF are bitmap fonts. I think the best way to get a great PSF font is by creating it with a correct tool or find existing ones on the internet (type Linux Kernel .
There also are methods to convert TTF to PSF but I don't know if the result will be as good as an hand-made font.

(cd /usr/share/consolefonts && find . -type f -name '*.psf.gz'; ) |
    sed 's/.\/\(.*\).psf.gz/\1/' |
    sort |
    column 

https://www.reddit.com/r/linuxquestions/comments/7st7hz/any_way_to_convert_ttf_files_to_psf_files/

**Comment by nifanfa** [comment]
you can use my Btifont too

**Comment by nifanfa** [comment]
@MasterYuan418 我发了pullrequest的里面有效果图
https://github.com/CosmosOS/Cosmos/pull/1845

**Comment by nifanfa** [comment]
中文也能用

**Comment by MasterYuan418** [comment]
@nifanfa 也许你应该考虑一下合并到aura里面？不过难得看到一个中国人啊

**Comment by nifanfa** [comment]
不考虑了

**Comment by nifanfa** [comment]
我都不用cosmos了

**Comment by nifanfa** [comment]
https://github.com/nifanfa/MOSA-Core
@MasterYuan418

**Comment by nifanfa** [comment]
@MasterYuan418  cosmos的内存泄露是给我劝退了

**Comment by nifanfa** [comment]
@MasterYuan418  我之前做了个gui https://github.com/nifanfa/Cosmos-GUI-Sample 20秒必卡死

**Comment by MasterYuan418** [comment]
@nifanfa 非常感谢大佬的帮助...我看看能不能迁移Aura到MOSA上，话说MOSA和Cosmos兼容吗？

**Comment by nifanfa** [comment]
@MasterYuan418 
加个qq?

**Comment by nifanfa** [comment]
3244735564
