### ISSUE TITLE
Cannot scroll screen

### ISSUE THREAD

**Issue by MasterYuan418** [aura-systems/Aura-Operating-System#213]
I run some command at the console.Then the console's screen was fulled and can't scroll.
![屏幕截图 2021-08-19 091335.png](https://i.loli.net/2021/08/19/UaApmDBFCHr74kG.png)

**Comment by valentinbreiz** [comment]
Hello @MasterYuan418, is it the ISO from the last release or did you try to compile Aura by yourself?

**Comment by MasterYuan418** [comment]
It's compile Aura by myself.

**Comment by valentinbreiz** [comment]
And what is you VM?

**Comment by MasterYuan418** [comment]
@valentinbreiz VMware Workstation 16 Pro(ver. 16.1.0 build-17198959)
My system:  Windows 10 Pro 64bit (19043.1110) 16GB DDR4 RAM

**Comment by Kiirx** [comment]
Is it still happening with last commits? @MasterYuan418 if it does, close the issue.

**Comment by valentinbreiz** [comment]
This is now fixed.
