### ISSUE TITLE
AuraOS build

### ISSUE THREAD

**Issue by DoorsDev** [aura-systems/Aura-Operating-System#216]
Hi, i want to build AuraOS, but it gives me lots of errors.
I try to build with the custom cosmos
but i only have hyper-v not vmware
is anything im doing wrong???
Thanks
DoorsDev.

**Comment by MasterYuan418** [comment]
Can you give a screenshots when errors occured?
  If you want to build custom cosmos,try to follow this page:[https://github.com/aura-systems/Aura-Operating-System/wiki/Compiling-Aura-OS](This)
  I will continue to follow up your issues.

**Comment by DoorsDev** [comment]
Master Yuan, i not builded it but from the file structure, it seems to only suport vmware, this is true???
Thanks
DALVES2012

**Comment by MasterYuan418** [comment]
Ummmm.... In my opinion,it's just to use VMWare in debug.The Cosmos will build a ISO file.
  Can you give a error report log file?

**Comment by geomtech** [comment]
Hi @DoorsDev 
In the project settings, you can set a setting if you want to debug it in VMWare or just creating an ISO file.
I recommend you to create the ISO file and running it in Hyper-V.
We didn't test if it was working in Hyper-V, it will depend if the graphical console is supported by Hyper-V.
We would like to have your feedback if it's working or not... Thanks.

If you have some errors in visual studio when you want to build Aura OS with custom Cosmos, please report them there.

Best regards,
Alexy DA CRUZ

**Comment by DoorsDev** [comment]
Thanks for the help
DoorsDev

**Comment by DoorsDev** [comment]
Hi, how to install???
Is downloading the cosmos files and replace the existing files with the auraOS
Or just copying the auraOS folder
Thanks DoorsDev

**Comment by geomtech** [comment]
> Hi, how to install???
> 
> Is downloading the cosmos files and replace the existing files with the auraOS
> 
> Or just copying the auraOS folder
> 
> Thanks DoorsDev

Hi,

You can follow this page on the wiki, you'll be able to compile Aura OS with custom Cosmos OS.

[https://github.com/aura-systems/Aura-Operating-System/wiki/Compiling-Aura-OS](https://github.com/aura-systems/Aura-Operating-System/wiki/Compiling-Aura-OS)

**Comment by DoorsDev** [comment]
Sorry to incomoding
Thanks, DoorsDev
