### ISSUE TITLE
OS doesn't build

### ISSUE THREAD

**Issue by tihonryzhikov** [aura-systems/Aura-Operating-System#226]
I installed the COSMOS version for Aura, the OS itself is going fine, but if I try to build my own, it will throw an IL2CPU exception.
![image](https://user-images.githubusercontent.com/66679206/147411073-9e75b78e-0763-4752-bfdd-5fc709b0a5b3.png)
Why?

**Comment by valentinbreiz** [comment]
Hello, are you using our forks of IL2CPU, Cosmos, XSharp and Common?

**Comment by tihonryzhikov** [comment]
> Hello, are you using our forks of IL2CPU, Cosmos, XSharp and Common? 

Yes.

**Comment by Kiirx** [comment]
@tihonryzhikov try building with last commits if you're still interested
