### ISSUE TITLE
When compiling Cosmos, error happend.(CS1705)

### ISSUE THREAD

**Issue by MasterYuan418** [aura-systems/Aura-Operating-System#233]
I'm compiling Cosmos and I got an error:
`CSC : error CS1705: ▒Û╩Â╬¬í░IL2CPU.Debug.Symbols.Net48, Version=10.0.0.0, Culture=neutral, PublicKeyToken=d73cc016e472ae16í▒Á─│╠ð‗╝»í░IL2CPU.Debug.Symbols.Net48í▒╦¨╩╣Ë├Á─í░System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3aí▒░µ▒¥©▀Ë┌╦¨Ê²Ë├Á─▒Û╩Â╬¬í░System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3aí▒Á─│╠ð‗╝»í░System.Runtimeí▒ [D:\Cosmosbuild\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj]`

Should I do something to fix?

**Comment by valentinbreiz** [comment]
That's a bug in Cosmos, just try again and again until the devkit pass the "build" part

**Comment by MasterYuan418** [comment]
ummm, I try again and I got an error message like 'NETSDK1005`, are they same?

**Comment by valentinbreiz** [comment]
What is the error?

**Comment by MasterYuan418** [comment]
OK thanks 👍
