### ISSUE TITLE
I try to use another font, but "red screen" happend.

### ISSUE THREAD

**Issue by MasterYuan418** [aura-systems/Aura-Operating-System#234]
I try to use psf font converted by myself, and I try to write text use int.
  this is my code:
  `Console.Write(0x4D);`
  ` Console.Write(6587);`
  But when I start using it in VMWare, it suddenly crashed.
  I have confirmed that the font contains these two encodings.
  What should I do?

**Comment by valentinbreiz** [comment]
Where did you get this PC Screen Font?

**Comment by MasterYuan418** [comment]
@valentinbreiz I converted by OTF font.OTF font is `Source Han Sans` because it support Chinese.
[Uploading font.zip…]()

**Comment by MasterYuan418** [comment]
Also, When I try to use `Encoding.Default.GetString()`,it also crash.
