### ISSUE TITLE
How did you get a custom font working in AuraOS

### ISSUE THREAD

**Issue by Dell-Optiplex-390** [aura-systems/Aura-Operating-System#238]
Hello, AuraOS is an amazing operating system and I've used it on my old computer and in VMWare. But I wanted to ask how did you get a custom font to work for the console? I took a look at the source code but I couldn't find the code for it. If you can please leave a YouTube link or a guide on how you did it. Thanks

**Comment by MasterYuan418** [comment]
@RSTPlays I'm sorry I didn't see your question in time.
The source code is here:
In `Graphics.cs` line 40
`font = PCScreenFont.LoadFont`
This will load font from base64 string.

**Comment by MasterYuan418** [comment]
@RSTPlays May be you should check if you're the latest version of aura system?
To clone the latest version,use `git clone https://github.com/aura-systems/Aura-Operating-System`
In `System\Graphics\Graphics.cs`
![图片](https://user-images.githubusercontent.com/58651976/153688125-c3a44205-aba2-4aaa-8611-692a6401ba0a.png)
![图片](https://user-images.githubusercontent.com/58651976/153688188-f6de7a75-3419-4a4e-9bbb-efb90dcd7623.png)
I will follow up on this issue until it is resolved.

**Comment by RSTPlays** [comment]
I think Aura made a gui of there operating system. I’ll try and use an older version

**Comment by MasterYuan418** [comment]
Yeah...This is a feasible way.
