### ISSUE TITLE
Hello, got a development question.

### ISSUE THREAD

**Issue by djlw78** [aura-systems/Aura-Operating-System#24]
I would like to help you, with Alve-Operating-System. I have some idea's to make thing's better without changing anything you are doing correct.  I am very flexible with development. I am pretty fluent in c#; If you invite me on-board there are something's I can add in that you probably will appreciate a lot.

Thank you.

**Comment by valentinbreiz** [comment]
Good evening!
Alexy and I are happy to get any help on this project. So, of course, you can help us. Let's discuss by email to see details about your entry as organization's member ;)

**Comment by djlw78** [comment]
@valentinbreiz ah yes. I send you an email regarding this.

**Comment by geomtech** [comment]
**This issue will stay open for anyone who want to help on this project :)**

**Comment by Project-Magenta** [comment]
Me!

**Comment by djlw78** [comment]
@Project-Magenta you man need to explain a bit more. Not just "me".

**Comment by Project-Magenta** [comment]
I can help with apps

**Comment by geomtech** [comment]
Can we talk by mail ? dacruzalexy@gmail.com

**Comment by Project-Magenta** [comment]
mountleafy@hotmail.com

**Comment by Project-Magenta** [comment]
actually it's outlook.com

**Comment by ROBLOXVIP735** [comment]
I would enjoy helping by writing a few programs for this operating system, but I would need some help.

**Comment by djlw78** [comment]
@valentinbreiz @geomtech I'm not qualified to answer @ROBLOXVIP735 's question due to his age. I don't do well with kids.

**Comment by valentinbreiz** [comment]
Hello @ROBLOXVIP735, @djlw78 and I were working on a binary loader. You can see the pull request here https://github.com/aura-systems/Aura-Operating-System/pull/38. To write your own program and use it in Aura you will need to compile it with this: https://github.com/aura-systems/Aura-Executable.

But I won't recommend you for now to write programs for Aura, applications are not ready. We just achieved multitask but we don't have user mode, the system calls are messy.. (And there are only two syscalls for your program, printf and fget, there is a lot of work to do..)

But if you want to contribute you can try to port libc with custom system calls for Aura, like we did for printf for example.

**Comment by djlw78** [comment]
Crp wrong button

**Comment by linuxcodefire** [comment]
me twoooo =D

**Comment by djlw78** [comment]
@linuxcodefire please shut up

**Comment by linuxcodefire** [comment]
NO! MY BIG DADDY SAID I CAN BE ANYTHING HE TREATS ME RIGHT YOU SHUT UP!!!

**Comment by linuxcodefire** [comment]
%force delete ~4%

**Comment by Project-Magenta** [comment]
Please shut up.

**Comment by djlw78** [comment]
?

**Comment by linuxcodefire** [comment]
CONFIRMED

**Comment by geomtech** [comment]
Closed. If you want to help the project, you can go on [our discord server](https://discord.gg/cbmME6M)
