### ISSUE TITLE
MSB600 Error

### ISSUE THREAD

**Issue by MasterYuan418** [aura-systems/Aura-Operating-System#240]
When I'm trying to compile Aura,MSB 600 happend.
  
![图片](https://user-images.githubusercontent.com/58651976/153689570-dfe91316-3eeb-43f4-b08c-23bd956a7bd2.png)

`MSB600 'nasm.exe' is exited,Code 1`

What wrong with that?

**Comment by valentinbreiz** [comment]
Did you install the last Cosmos userkit or devkit? We don't use nasm anymore we switched to yasm in last commits

**Comment by MasterYuan418** [comment]
@valentinbreiz Yes,I follow the wiki and clone all the repo.And error still happend.

**Comment by valentinbreiz** [comment]
Because you need official Cosmos repositories not Aura's forks
I will update the documentation

**Comment by MasterYuan418** [comment]
OK, But compile still failed. I will open a new issue.
