### ISSUE TITLE
QUESTION : How you integrate resources in AuraOS?

### ISSUE THREAD

**Issue by RaphMar2021** [aura-systems/Aura-Operating-System#245]
How you integrate resources in AuraOS?

Because i make an GUI OS

**Comment by valentinbreiz** [comment]
[ManifestResourceStream(ResourceName = "Aura_OS.Resources.AuraLogo.bmp")] 
public static byte[] AuraImage;

And in your .csproj:
<ItemGroup>
      <EmbeddedResource Include="Resources\AuraLogo.bmp" />
</ItemGroup>
