### ISSUE TITLE
Can i get the Canvas.ScrollUp function code?

### ISSUE THREAD

**Issue by RaphMar2021** [aura-systems/Aura-Operating-System#246]
Hi! I'm try to make a Linux C# version with Cosmos.
and i need the graphical console but i find nothing in the Cosmos AuraOS version fork.

Where is the code of this function?

PS : I find this : 
`public virtual void ScrollUp() { }`

**Comment by valentinbreiz** [comment]
Yes of course, you can find it here: https://github.com/aura-systems/Cosmos/blob/master/source/Cosmos.HAL2/Drivers/Video/VBEDriver.cs#L310
