### ISSUE TITLE
When I try using GUI it gives an error

### ISSUE THREAD

**Issue by KittenPixel-cell** [aura-systems/Aura-Operating-System#249]
when I wanted to use gui it gives an error
![image](https://user-images.githubusercontent.com/79544605/233847945-6a403575-fb55-4cf0-bdd9-fb98bbb90b81.png)
I press enter I choose english

It is this

![image](https://user-images.githubusercontent.com/79544605/233847975-5e6325c2-f8ef-44f5-ab06-7ae6cde72ef0.png)

**Comment by valentinbreiz** [comment]
What is the error? You're using graphic mode
