### ISSUE TITLE
I'm stuck on booting console

### ISSUE THREAD

**Issue by LeVraiStagiaire** [aura-systems/Aura-Operating-System#255]
Hello, I tried to run the project into Qemu, but I'm stuck here : 
![image](https://github.com/aura-systems/Aura-Operating-System/assets/48404856/08fd543e-3417-4d41-a8aa-87cc03f0e4a0)

**Comment by valentinbreiz** [comment]
Hello,
I think VBE may not be implemented again. We use VMWare SVGAII for graphics and it's not supported by QEMU, only VBE is for graphics.

**Comment by LeVraiStagiaire** [comment]
I've tried on VMWare too, but i've the same issue

**Comment by LeVraiStagiaire** [comment]
After I built the project
