### ISSUE TITLE
[P1] Ping ext source IP problem

### ISSUE THREAD

**Issue by geomtech** [aura-systems/Aura-Operating-System#96]
High priority level.

Need to fix that issue. Everybody can work on it ! :)

Actually when we're making a ping to an another computer in the same network, it works !
But when we try to ping ext like 8.8.8.8, the source ip is replaced by 0.0.0.0
So the ping stuck and we have to reboot Aura.

In all the cases, 8.8.8.8 will be unreachable because Aura doesn't know yet how to exit the local network, okay ?

If you have some questions, you can comment this issue.
Thanks for your support !

**Comment by Project-Magenta** [comment]
.-.

**Comment by geomtech** [comment]
Issue solved !
